<?php

namespace App\Helpers;

class CubanLocations
{
    public static function provincias(): array
    {
        return [
            'Pinar_del_Rio' => 'Pinar del Río',
            'Artemisa' => 'Artemisa',
            'La_Habana' => 'La Habana',
            'Mayabeque' => 'Mayabeque',
            'Matanzas' => 'Matanzas',
            'Cienfuegos' => 'Cienfuegos',
            'Villa_Clara' => 'Villa Clara',
            'Sancti_Spiritus' => 'Sancti Spíritus',
            'Ciego_de_Avila' => 'Ciego de Ávila',
            'Camaguey' => 'Camagüey',
            'Las_Tunas' => 'Las Tunas',
            'Holguin' => 'Holguín',
            'Granma' => 'Granma',
            'Santiago_de_Cuba' => 'Santiago de Cuba',
            'Guantanamo' => 'Guantánamo',
            'Isla_de_la_Juventud' => 'Isla de la Juventud',
        ];
    }

    public static function municipios(string $provincia): array
    {
        $municipios = [
            'Pinar_del_Rio' => [
                'Pinar_del_Rio' => 'Pinar del Río',
                'Consolacion_del_Sur' => 'Consolación del Sur',
                'Guane' => 'Guane',
                'La_Palma' => 'La Palma',
                'Los_Palacios' => 'Los Palacios',
                'Mantua' => 'Mantua',
                'Minas_de_Matahambre' => 'Minas de Matahambre',
                'San_Juan_y_Martinez' => 'San Juan y Martínez',
                'San_Luis' => 'San Luis',
                'Sandino' => 'Sandino',
                'Vinales' => 'Viñales',
            ],
            'Artemisa' => [
                'Artemisa' => 'Artemisa',
                'Alquizar' => 'Alquízar',
                'Bauta' => 'Bauta',
                'Caimito' => 'Caimito',
                'Candelaria' => 'Candelaria',
                'Guanajay' => 'Guanajay',
                'Guira_de_Melena' => 'Güira de Melena',
                'Mariel' => 'Mariel',
                'San_Antonio_de_los_Banos' => 'San Antonio de los Baños',
                'San_Cristobal' => 'San Cristóbal',
                'Bahia_Honda' => 'Bahía Honda',
            ],
            'La_Habana' => [
                'Arroyo_Naranjo' => 'Arroyo Naranjo',
                'Boyeros' => 'Boyeros',
                'Centro_Habana' => 'Centro Habana',
                'Cerro' => 'Cerro',
                'Cotorro' => 'Cotorro',
                'Diez_de_Octubre' => 'Diez de Octubre',
                'Guanabacoa' => 'Guanabacoa',
                'La_Habana_del_Este' => 'La Habana del Este',
                'La_Habana_Vieja' => 'La Habana Vieja',
                'La_Lisa' => 'La Lisa',
                'Marianao' => 'Marianao',
                'Playa' => 'Playa',
                'Plaza_de_la_Revolucion' => 'Plaza de la Revolución',
                'Regla' => 'Regla',
                'San_Miguel_del_Padron' => 'San Miguel del Padrón',
            ],
            'Mayabeque' => [
                'San_Jose_de_las_Lajas' => 'San José de las Lajas',
                'Batabano' => 'Batabanó',
                'Bejucal' => 'Bejucal',
                'Guines' => 'Güines',
                'Jaruco' => 'Jaruco',
                'Madruga' => 'Madruga',
                'Melena_del_Sur' => 'Melena del Sur',
                'Nueva_Paz' => 'Nueva Paz',
                'Quivican' => 'Quivicán',
                'San_Nicolas' => 'San Nicolás',
                'Santa_Cruz_del_Norte' => 'Santa Cruz del Norte',
            ],
            'Matanzas' => [
                'Matanzas' => 'Matanzas',
                'Calimete' => 'Calimete',
                'Cardenas' => 'Cárdenas',
                'Cienaga_de_Zapata' => 'Ciénaga de Zapata',
                'Colon' => 'Colón',
                'Jaguey_Grande' => 'Jagüey Grande',
                'Jovellanos' => 'Jovellanos',
                'Limonar' => 'Limonar',
                'Los_Arabos' => 'Los Arabos',
                'Marti' => 'Martí',
                'Pedro_Betancourt' => 'Pedro Betancourt',
                'Perico' => 'Perico',
                'Union_de_Reyes' => 'Unión de Reyes',
            ],
            'Cienfuegos' => [
                'Cienfuegos' => 'Cienfuegos',
                'Abreus' => 'Abreus',
                'Aguada_de_Pasajeros' => 'Aguada de Pasajeros',
                'Cruces' => 'Cruces',
                'Cumanayagua' => 'Cumanayagua',
                'Lajas' => 'Lajas',
                'Palmira' => 'Palmira',
                'Rodas' => 'Rodas',
            ],
            'Villa_Clara' => [
                'Santa_Clara' => 'Santa Clara',
                'Caibarien' => 'Caibarién',
                'Camajuani' => 'Camajuaní',
                'Cifuentes' => 'Cifuentes',
                'Corralillo' => 'Corralillo',
                'Encrucijada' => 'Encrucijada',
                'Manicaragua' => 'Manicaragua',
                'Placetas' => 'Placetas',
                'Quemado_de_Guines' => 'Quemado de Güines',
                'Ranchuelo' => 'Ranchuelo',
                'Remedios' => 'Remedios',
                'Sagua_la_Grande' => 'Sagua la Grande',
                'Santo_Domingo' => 'Santo Domingo',
            ],
            'Sancti_Spiritus' => [
                'Sancti_Spiritus' => 'Sancti Spíritus',
                'Cabaiguan' => 'Cabaiguán',
                'Fomento' => 'Fomento',
                'Jatibonico' => 'Jatibonico',
                'La_Sierpe' => 'La Sierpe',
                'Taguasco' => 'Taguasco',
                'Trinidad' => 'Trinidad',
                'Yaguajay' => 'Yaguajay',
            ],
            'Ciego_de_Avila' => [
                'Ciego_de_Avila' => 'Ciego de Ávila',
                'Baragua' => 'Baraguá',
                'Bolivia' => 'Bolivia',
                'Chambas' => 'Chambas',
                'Ciro_Redondo' => 'Ciro Redondo',
                'Florencia' => 'Florencia',
                'Majagua' => 'Majagua',
                'Moron' => 'Morón',
                'Primero_de_Enero' => 'Primero de Enero',
                'Venezuela' => 'Venezuela',
            ],
            'Camaguey' => [
                'Camaguey' => 'Camagüey',
                'Carlos_M_de_Cespedes' => 'Carlos M. de Céspedes',
                'Esmeralda' => 'Esmeralda',
                'Florida' => 'Florida',
                'Guaimaro' => 'Guáimaro',
                'Jimaguayu' => 'Jimaguayú',
                'Minas' => 'Minas',
                'Najasa' => 'Najasa',
                'Nuevitas' => 'Nuevitas',
                'Santa_Cruz_del_Sur' => 'Santa Cruz del Sur',
                'Sibanicu' => 'Sibanicú',
                'Sierra_de_Cubitas' => 'Sierra de Cubitas',
                'Vertientes' => 'Vertientes',
            ],
            'Las_Tunas' => [
                'Las_Tunas' => 'Las Tunas',
                'Amancio' => 'Amancio',
                'Colombia' => 'Colombia',
                'Jesus_Menendez' => 'Jesús Menéndez',
                'Jobabo' => 'Jobabo',
                'Majibacoa' => 'Majibacoa',
                'Manati' => 'Manatí',
                'Puerto_Padre' => 'Puerto Padre',
            ],
            'Holguin' => [
                'Holguin' => 'Holguín',
                'Antilla' => 'Antilla',
                'Baguanos' => 'Báguanos',
                'Banes' => 'Banes',
                'Cacocum' => 'Cacocum',
                'Calixto_Garcia' => 'Calixto García',
                'Cueto' => 'Cueto',
                'Frank_Pais' => 'Frank País',
                'Gibara' => 'Gibara',
                'Mayari' => 'Mayarí',
                'Moa' => 'Moa',
                'Rafael_Freyre' => 'Rafael Freyre',
                'Sagua_de_Tanamo' => 'Sagua de Tánamo',
                'Urbano_Noris' => 'Urbano Noris',
            ],
            'Granma' => [
                'Bayamo' => 'Bayamo',
                'Bartolome_Maso' => 'Bartolomé Masó',
                'Buey_Arriba' => 'Buey Arriba',
                'Campechuela' => 'Campechuela',
                'Cauto_Cristo' => 'Cauto Cristo',
                'Guisa' => 'Guisa',
                'Jiguani' => 'Jiguaní',
                'Manzanillo' => 'Manzanillo',
                'Media_Luna' => 'Media Luna',
                'Niquero' => 'Niquero',
                'Pilon' => 'Pilón',
                'Rio_Cauto' => 'Río Cauto',
                'Yara' => 'Yara',
            ],
            'Santiago_de_Cuba' => [
                'Santiago_de_Cuba' => 'Santiago de Cuba',
                'Contramaestre' => 'Contramaestre',
                'Guama' => 'Guamá',
                'Mella' => 'Mella',
                'Palma_Soriano' => 'Palma Soriano',
                'San_Luis' => 'San Luis',
                'Segundo_Frente' => 'Segundo Frente',
                'Songo_La_Maya' => 'Songo-La Maya',
                'Tercer_Frente' => 'Tercer Frente',
            ],
            'Guantanamo' => [
                'Guantanamo' => 'Guantánamo',
                'Baracoa' => 'Baracoa',
                'Caimanera' => 'Caimanera',
                'El_Salvador' => 'El Salvador',
                'Imias' => 'Imías',
                'Maisi' => 'Maisí',
                'Manuel_Tames' => 'Manuel Tames',
                'Niceto_Perez' => 'Niceto Pérez',
                'San_Antonio_del_Sur' => 'San Antonio del Sur',
                'Yateras' => 'Yateras',
            ],
            'Isla_de_la_Juventud' => [
                'Isla_de_la_Juventud' => 'Isla de la Juventud',
            ],
        ];

        return $municipios[$provincia] ?? [];
    }
}